version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn -w 4 --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.dev_env.prod
    volumes:
      - sqlite-data:/home/app/web
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  sqlite-data: